CREATE DATABASE TRANSPORT_3 ;

USE TRANSPORT_3 ;

CREATE TABLE DRIVER_5
(
DRIVER_IDD INT PRIMARY KEY,
DRIVER_NAME VARCHAR(78),
DRIVER_PICKUP VARCHAR(67),
DRIVER_DROPOFF VARCHAR(65),
DRIVER_FARE INT
);

SELECT * FROM DRIVER_5 ;

INSERT INTO DRIVER_5 VALUES ("1","RADHE","VASTRAL","MANINAGAR","65");
INSERT INTO DRIVER_5 VALUES ("2","SHYAM","DARIYAPUR","SULTANPUR","70");
INSERT INTO DRIVER_5 VALUES ("3","SAHAY","SAHIBAUGH","GANDHINAGAR","80");
INSERT INTO DRIVER_5 VALUES ("4","MUNNA","CHARBAUGH","AALAMBAUGH","90");
INSERT INTO DRIVER_5 VALUES ("5","RAJU","KNIT","KNITM","110");
INSERT INTO DRIVER_5 VALUES ("6","KEWAL","CHAROD","ROADIYE","115");
INSERT INTO DRIVER_5 VALUES ("7","JIGNESH","CIVIL","ANAND","125");
INSERT INTO DRIVER_5 VALUES ("8","JAY","CPROAD","CGROAD","130");
INSERT INTO DRIVER_5 VALUES ("9","RAJESH","NIRANT","RABARI","150");
INSERT INTO DRIVER_5 VALUES ("10","RITIK","APPAREL","AMARIWADI","50");
INSERT INTO DRIVER_5 VALUES ("11","RIYAAN","JAMNAGAR","RAJKOT","35");



CREATE TABLE PASSENGER_1
(
PASSENGER_ID INT PRIMARY KEY,
PASSENGER_NAME VARCHAR(78),
PASSENGER_GENDER ENUM("M","F"),
PA_VEHICLE ENUM("AVAILABLE","CANCELLED","RESERVED")
);

INSERT INTO PASSENGER_1 VALUES("101","AJAY", "M","RESERVED");
INSERT INTO PASSENGER_1 VALUES("102","NEHA", "F","AVAILABLE");
INSERT INTO PASSENGER_1 VALUES("103","VIJAY", "M","CANCELLED");
INSERT INTO PASSENGER_1 VALUES("104","JOY", "M","CANCELLED");
INSERT INTO PASSENGER_1 VALUES("105","NISHA", "F","CANCELLED");
INSERT INTO PASSENGER_1 VALUES("106","VARTIKA", "F","CANCELLED");
INSERT INTO PASSENGER_1 VALUES("107","VANJAY", "M","CANCELLED");
INSERT INTO PASSENGER_1 VALUES("108","KULBHUSHAN", "M","CANCELLED");
INSERT INTO PASSENGER_1 VALUES("109","PARUL", "F","CANCELLED");
INSERT INTO PASSENGER_1 VALUES("110","NEHA", "F","CANCELLED");
INSERT INTO PASSENGER_1 VALUES("111","SHRADDHA", "F","RESERVED");
INSERT INTO PASSENGER_1 VALUES("112","ABHISHEK", "M","AVAILABLE");
INSERT INTO PASSENGER_1 VALUES("113","SHIVALI", "F","RESERVED");
INSERT INTO PASSENGER_1 VALUES("114","KRISHNA", "M","CANCELLED");
INSERT INTO PASSENGER_1 VALUES("115","RAMAN", "M","RESERVED");
INSERT INTO PASSENGER_1 VALUES("116","SUHANSHI", "F","CANCELLED");
INSERT INTO PASSENGER_1 VALUES("117","AKRITI", "M","AVAILABLE");
INSERT INTO PASSENGER_1 VALUES("118","SNEHA", "F","RESERVED");
INSERT INTO PASSENGER_1 VALUES("119","POOJA", "F","AVAILABLE");
INSERT INTO PASSENGER_1 VALUES("120","FAIZ", "M","CANCELLED");
INSERT INTO PASSENGER_1 VALUES("121","ANKIT", "M","RESERVED");
INSERT INTO PASSENGER_1 VALUES("122","SHIVANSH", "M","AVAILABLE");
INSERT INTO PASSENGER_1 VALUES("123","AMIT", "M","RESERVED");
INSERT INTO PASSENGER_1 VALUES("124","AASHI", "F","AVAILABLE");
INSERT INTO PASSENGER_1 VALUES("125","KAVI", "M","RESERVED");
INSERT INTO PASSENGER_1 VALUES("126","PAAKHI", "F","CANCELLED");

SELECT * FROM DRIVER_5
LEFT JOIN PASSENGER_1 
ON DRIVER_5.DRIVER_IDD = PASSENGER_1.PASSENGER_ID ;

SELECT* FROM DRIVER_5 ;

SELECT * FROM DRIVER_5
LEFT JOIN PASSENGER_1 ON
DRIVER_5.DRIVER_IDD = PASSENGER_1.PASSENGER_ID ;







